name: Automated Testing on Pi4
on:
    push:
        branches: testing
jobs:
    PiTests:
      name: pitests
      runs-on: testpi4
      strategy:
        matrix:
          python-version: ["3.7"] #, "3.8", "3.9", "3.10", "3.11"]
      steps:
        - uses: actions/checkout@v3 # cant upgrade as node20 not supported on raspian buster
        - name: run tests
          run: |
              RMSDIR=$(pwd)
              DATADIR=~/RMS_data/testdata
              mkdir -p $DATADIR
              rsync -avz thelinux:/data3/testing/RMS_data/ $DATADIR
              source ~/vRMS/bin/activate
              python -V 
              pip install -r requirements.txt
              ./Tests/testFRbin.sh $RMSDIR $DATADIR
              ./Tests/testGenMP4s.sh $RMSDIR $DATADIR
